SKILLS = [
    "python",
    "sql",
    "pandas",
    "numpy",
    "scikit-learn",
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "nlp",
    "tensorflow",
    "pytorch",
    "keras",
    "feature engineering",
    "data preprocessing",
    "data analysis",
    "statistics",
    "power bi",
    "excel",
    "git",
    "github",
    "streamlit",
    "flask"
]